const fs=require('fs'),assert=require('assert');const {chromium}=require('C:/Users/无语/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const server=require('http').createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(fs.readFileSync('G:/youhegaojian/macro-mind-engine/phase1/batch_pilot/review_ui_v2/HUMAN_REVIEW.html'));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const b=await chromium.launch({channel:'msedge',headless:true});try{const c=await b.newContext({acceptDownloads:true});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port);await p.locator('#importFile').setInputFiles('C:/Users/无语/Downloads/MacroMind_首五期审阅_2026-10-03T08-39-18-728Z.json');await p.locator('#acceptImport').click();assert((await p.locator('#progress').innerText()).includes('已作判定 10 /'));console.log('PASS actual human file validates and restores10 decisions');
const support=await p.evaluate(async()=>{try{window.qaDir=await navigator.storage.getDirectory();window.showDirectoryPicker=async()=>qaDir;return {opfs:true};}catch(e){return {opfs:false,error:e.message};}});console.log(support);
if(!support.opfs)throw Error('OPFS unavailable');
await p.locator('#chooseDir').click();await p.waitForFunction(()=>document.getElementById('directoryStatus').textContent.includes('已记住选择'));await p.locator('#export').click();await p.waitForFunction(()=>document.getElementById('message').textContent.startsWith('已保存并核对'));await p.locator('#export').click();await p.waitForTimeout(250);let files=await p.evaluate(async()=>{let all=[];for await(const [day,h]of qaDir.entries()){if(h.kind==='directory')for await(const [name,f]of h.entries())all.push({day,name,body:JSON.parse(await(await f.getFile()).text())});}return all;});assert.equal(files.length,2);assert(files.every(f=>f.name.includes('10of2657')&&f.body.records.filter(r=>r.decision!=='pending').length===10));assert.notEqual(files[0].name,files[1].name);console.log('PASS actual FileSystemDirectoryHandle writes dated unique files and reads back exact content');
await p.reload();await p.waitForFunction(()=>document.getElementById('directoryStatus').textContent.includes('已恢复保存目录'));await p.locator('#export').click();await p.waitForFunction(()=>document.getElementById('message').textContent.startsWith('已保存并核对'));console.log('PASS IndexedDB persists native directory handle across reload');
await p.evaluate(()=>{directoryHandle={name:'拒绝写入测试',queryPermission:async()=> 'denied',requestPermission:async()=> 'denied'};});await p.locator('#export').click();await p.waitForFunction(()=>document.getElementById('message').textContent.startsWith('导出未完成'));assert((await p.locator('#progress').innerText()).includes('已作判定 10 /'));console.log('PASS denied directory write reports failure and preserves feedback');
await p.locator('#useDownloads').click();await p.waitForFunction(()=>document.getElementById('directoryStatus').textContent.includes('默认下载'));const dl=p.waitForEvent('download');await p.locator('#export').click();const download=await dl;assert(download.suggestedFilename().includes('10of2657'));console.log('PASS explicit download fallback with organized naming');assert.equal(errors.length,0);fs.writeFileSync('G:/youhegaojian/review-ui-qa/export-v3/directory-results.json',JSON.stringify({status:'PASS',checks:6,real_human_import:true,native_file_system_write:true,picker:'Replaced OS picker with native browser-private directory handle for automated testing; actual user path selection remains user action',test_directory:'Isolated browser context OPFS; not user review archive',errors},null,2));await p.screenshot({path:'G:/youhegaojian/review-ui-qa/export-v3/directory-controls.png'});
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
