const fs=require('fs');const assert=require('assert');const {pathToFileURL}=require('url');const {chromium}=require('C:/Users/无语/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='G:/youhegaojian',qa=root+'/review-ui-qa/export-v3',ui=root+'/macro-mind-engine/phase1/batch_pilot/review_ui_v2',url=pathToFileURL(ui+'/HUMAN_REVIEW.html').href;
const results=[];function ok(name){results.push({name,status:'PASS'});console.log('PASS',name);}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(url);await page.waitForSelector('article');assert((await page.title()).includes('人工审阅'));assert.equal(page.url(),url);assert.equal(await page.locator('article').count(),10);ok('page identity, meaningful render,10 priority chains');
await page.screenshot({path:qa+'/desktop.png'});
await page.locator('#reviewer').fill('QA测试者（测试数据）');const card=page.locator('article').first();const id=await card.getAttribute('data-id');await card.locator('select').first().selectOption('change');await card.locator('textarea').nth(0).fill('测试意见：不要把可能改成一定。<script>window.bad=1</script>');await card.locator('textarea').nth(1).fill('测试修正');await card.locator('textarea').nth(2).fill('测试证据 cue2');await page.locator('#save').click();assert((await page.locator('#storageStatus').innerText()).includes('已保存'));await page.reload();await page.waitForSelector('article');assert.equal(await page.locator('article').first().locator('select').first().inputValue(),'change');assert((await page.locator('article').first().locator('textarea').first().inputValue()).includes('测试意见'));assert.equal(await page.evaluate(()=>window.bad),undefined);ok('decision,three text fields,reviewer,save and reload; text not executed');
const categories=await page.locator('#kind option').evaluateAll(os=>os.map(o=>o.value).filter(v=>v&&v!=='priority'));
for(const category of categories){await page.locator('#kind').selectOption(category);assert(await page.locator('article').count()>0);const first=page.locator('article').first();const choices=await first.locator('select').first().locator('option').evaluateAll(os=>os.map(o=>o.value));await first.locator('select').first().selectOption(choices[1]);await first.locator('textarea').first().fill('QA类别测试 '+category);}
ok('all14 categories have functioning decisions and opinion fields');
await page.locator('#kind').selectOption('新闻关联');await page.locator('article').first().locator('select').nth(1).selectOption('current_read');ok('news content verification separate from citation judgment');
await page.locator('#kind').selectOption('字幕覆盖');await page.locator('#episode').selectOption('EP005');assert((await page.locator('#pageInfo').innerText()).includes('510'));await page.locator('#next').click();assert((await page.locator('#pageInfo').innerText()).includes('第 2'));await page.locator('#search').fill('不存在的测试词zzzz');assert.equal(await page.locator('article').count(),0);await page.locator('#search').fill('');await page.locator('#episode').selectOption('');await page.locator('#kind').selectOption('priority');ok('episode/category/search filters,empty state,pagination');
await page.locator('article').first().locator('summary').first().click();assert(await page.locator('article').first().locator('blockquote').first().isVisible());const vh=await page.locator('article').first().getByRole('link',{name:'打开原视频，从首个证据片段开始核听'}).getAttribute('href');assert(vh.startsWith('file:///G:/'));assert(vh.includes('#t='));await page.locator('article').first().scrollIntoViewIfNeeded();await page.screenshot({path:qa+'/evidence-form.png'});ok('original quote expansion and timestamped local video link');
let dl=page.waitForEvent('download');await page.locator('#export').click();const download=await dl;await download.saveAs(qa+'/test-feedback.json');const saved=JSON.parse(fs.readFileSync(qa+'/test-feedback.json','utf8'));assert.equal(saved.records.length,2657);assert(saved.records.find(r=>r.id===id).note.includes('QA类别测试'));assert.equal(saved.records.find(r=>r.id==='EP001-N01').content_status,'current_read');ok('actual JSON download contains all2657 IDs and edited fields');
dl=page.waitForEvent('download');await page.locator('#exportText').click();await(await dl).saveAs(qa+'/test-feedback.txt');assert(fs.readFileSync(qa+'/test-feedback.txt','utf8').includes('测试'));ok('readable TXT download');
const c2=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const p2=await c2.newPage();await p2.goto(url);await p2.locator('#importFile').setInputFiles(qa+'/test-feedback.json');await p2.locator('#cancelImport').click();assert((await p2.locator('#progress').innerText()).includes('已作判定 0 /'));await p2.locator('#importFile').setInputFiles(qa+'/test-feedback.json');await p2.locator('#acceptImport').click();assert.equal(await p2.locator('#reviewer').inputValue(),saved.reviewer);assert.equal(await p2.locator('article').first().locator('textarea').first().inputValue(),saved.records.find(r=>r.id===id).note);await p2.reload();assert((await p2.locator('#storageStatus').innerText()).includes('已恢复'));ok('cancel import unchanged;confirmed import and subsequent reload restore fields');
for(const [label,mutate]of [['wrong dataset',p=>p.dataset='bad'],['duplicate ID',p=>p.records[1]=p.records[0]],['invalid option',p=>p.records[0].decision='AUTO_ACCEPT'],['invalid text',p=>p.records[0].note={}]] ) {const bad=structuredClone(saved);mutate(bad);fs.writeFileSync(qa+'/bad.json',JSON.stringify(bad));const before=await p2.locator('#progress').innerText();await p2.locator('#importFile').setInputFiles(qa+'/bad.json');await p2.waitForFunction(()=>document.getElementById('message').textContent.startsWith('导入失败'));assert.equal(await p2.locator('#progress').innerText(),before);ok('reject '+label+' without mutation');}
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:qa+'/mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));ok('mobile390px no horizontal overflow');assert.equal(errors.length,0);ok('no browser console/page errors');
const blocked=await browser.newContext({acceptDownloads:true});await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Blocked','SecurityError');};});const bp=await blocked.newPage();await bp.goto(url);await bp.locator('article').first().locator('textarea').first().fill('存储禁用时保留');await bp.locator('#save').click();assert((await bp.locator('#storageStatus').innerText()).includes('未能保存'));let bd=bp.waitForEvent('download');await bp.locator('#export').click();await(await bd).saveAs(qa+'/storage-blocked.json');assert(JSON.parse(fs.readFileSync(qa+'/storage-blocked.json','utf8')).records.some(r=>r.note==='存储禁用时保留'));ok('storage denial clearly reported;JSON export still works');
fs.writeFileSync(qa+'/results.json',JSON.stringify({browser:'Edge headless via Playwright',browser_plugin:'Absent: Browser plugin not available',url,viewports:[[1440,1000],[390,844]],checks:results,console_errors:errors,limitations:['In-app browser-specific download UI not tested','Video link target inspected; audio content not reviewed','Test feedback is synthetic QA, not human approval']},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);fs.writeFileSync(qa+'/failure.txt',e.stack);process.exitCode=1;});
