const {chromium}=require('C:/Users/无语/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
const out='G:/youhegaojian/review-ui-qa/analyst001';
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text())});
 const checks=[];const check=(name,ok)=>{checks.push({name,pass:!!ok});if(!ok)throw Error(name)};
 await page.goto('http://127.0.0.1:8768/TRACE.html');
 check('identity', (await page.title())==='MacroMind｜五期美联储判断追踪');
 check('not_blank',await page.locator('h1').innerText()==='从讲话到数据，再到决策后的新问题');
 check('no_error_overlay',await page.locator('vite-error-overlay,nextjs-portal').count()===0);
 check('timeline_five',await page.locator('#timeline article').count()===5);
 check('evidence_cards_31',await page.locator('#evidence article').count()===31);
 await page.screenshot({path:out+'/desktop.png'});
 await page.locator('nav a[href="#connections"]').click();
 check('nav_scroll',await page.evaluate(()=>location.hash==='#connections'&&Math.abs(document.querySelector('#connections').getBoundingClientRect().top)<100));
 await page.locator('#L02 a[href="#EP008/T02"]').click();
 check('evidence_anchor',await page.evaluate(()=>location.hash==='#EP008/T02'));
 const card=page.locator('[id="EP008/T02"]');await card.locator('summary').click();
 check('evidence_open',await card.locator('details').getAttribute('open')!==null);
 check('quote_visible',await card.locator('blockquote').first().isVisible());
 check('video_cue_link',(await card.locator('a[target="_blank"]').getAttribute('href')).endsWith('?t=299'));
 await page.screenshot({path:out+'/evidence.png'});
 const badLinks=await page.locator('a[href^="#"]').evaluateAll(nodes=>nodes.filter(n=>!document.getElementById(n.getAttribute('href').slice(1))).map(n=>n.getAttribute('href')));
 check('all_internal_links_resolve',badLinks.length===0);
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8768/TRACE.html');
 check('mobile_no_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:out+'/mobile.png'});
 await page.locator('nav a[href="#methods"]').click();const method=page.locator('#methods details').first();await method.locator('summary').click();
 check('mobile_method_expands',await method.getAttribute('open')!==null);
 check('mobile_method_no_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 check('console_health',errors.length===0);
 fs.writeFileSync(out+'/result.json',JSON.stringify({browser:'Edge via Playwright',browser_availability:'Browser plugin not available',flow:'time line -> cross-period connection -> claim evidence -> video time anchor; mobile method expansion',url:page.url(),viewports:[[1440,1000],[390,844]],checks,errors},null,2));
 console.log(JSON.stringify({passed:checks.length,errors}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
