const {chromium}=require('C:/Users/无语/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert');
const dir='G:/youhegaojian/review-ui-qa/framework-v03-delta';
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 const page=await context.newPage(),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 const url='file:///G:/youhegaojian/macro-mind-engine/phase1/framework_review/v03_draft_002/REVIEW.html';
 await page.goto(url);assert.equal(await page.title(),'MacroMind · v0.3 两项修订复审');
 assert.equal(await page.locator('article').count(),6);
 assert.equal(await page.locator('select:disabled').count(),8);assert.equal(await page.locator('select:enabled').count(),4);
 assert((await page.locator('#progress').textContent()).includes('4 / 6'));checks.push('six cards; four approvals inherited; only two editable');
 await page.locator('#next').click();assert(page.url().endsWith('#C03'));checks.push('next pending C03');
 await page.locator('#C03 details').nth(1).locator('summary').click();
 assert((await page.locator('#C03 details').nth(1).textContent()).includes('配合'));checks.push('previous review readable');
 await page.locator('#C04 details').first().locator('summary').click();
 const quote=await page.locator('#C04 blockquote').nth(1).textContent();
 assert(quote.includes('193')===false || quote.length>1000);
 const popupWait=page.waitForEvent('popup');
 await page.locator('#C04 details').first().locator('a').nth(1).click();
 const popup=await popupWait;await popup.waitForLoadState();
 assert(popup.url().endsWith('468.html#cue-110'));
 assert.equal(await popup.locator('#cue-194').count(),1);assert.equal(await popup.locator('#cue-224').count(),1);
 checks.push('continuous 468 evidence plus full episode context anchored at cue 110');await popup.close();
 await page.locator('#C03 [data-field=fidelity]').selectOption('accept');await page.locator('#C03 [data-field=boundary]').selectOption('accept');
 await page.locator('#C04 [data-field=fidelity]').selectOption('revise');await page.locator('#C04 [data-field=boundary]').selectOption('accept');
 assert((await page.locator('#progress').textContent()).includes('5 / 6'));
 let wait=page.waitForEvent('download');await page.locator('#download').click();let d=await wait;await d.saveAs(dir+'/partial.json');
 assert.equal(JSON.parse(fs.readFileSync(dir+'/partial.json')).completed,5);
 await page.locator('#C04 [data-field=notes]').fill('测试意见：保留战略代价和替代选择。');
 await page.reload();assert((await page.locator('#C04 [data-field=notes]').inputValue()).includes('战略代价'));
 assert((await page.locator('#progress').textContent()).includes('6 / 6'));checks.push('note requirement, partial export and reload persistence');
 wait=page.waitForEvent('download');await page.locator('#download').click();d=await wait;await d.saveAs(dir+'/full.json');
 const packet=JSON.parse(fs.readFileSync(dir+'/full.json'));assert.equal(packet.completed,6);assert.equal(packet.activation,'NOT_ACTIVATED');assert.equal(packet.records[3].fidelity,'revise');
 page.on('dialog',d=>d.accept());await page.locator('#C04 [data-field=notes]').fill('changed');
 await page.locator('#file').setInputFiles(dir+'/full.json');
 await page.waitForFunction(()=>document.getElementById('status').textContent.includes('已导入'));
 assert((await page.locator('#C04 [data-field=notes]').inputValue()).includes('战略代价'));checks.push('full export/import; completion is not approval or activation');
 for(const kind of ['version','duplicate','unknown','inherited','invalid_decision']){
 const bad=structuredClone(packet);
 if(kind==='version')bad.draft_sha256='other';
 if(kind==='duplicate')bad.records[3].id='C03';
 if(kind==='unknown')bad.records[3].id='C99';
 if(kind==='inherited')bad.records[0].fidelity='reject';
 if(kind==='invalid_decision')bad.records[3].fidelity='automatic_pass';
 fs.writeFileSync(dir+'/'+kind+'.json',JSON.stringify(bad));
 await page.locator('#file').setInputFiles(dir+'/'+kind+'.json');
 await page.waitForFunction(()=>document.getElementById('status').textContent.includes('导入失败'));
 assert((await page.locator('#C04 [data-field=notes]').inputValue()).includes('战略代价'));checks.push(kind+' rejected atomically');
 }
 await page.evaluate(()=>localStorage.clear());await page.goto(url);
 await page.screenshot({path:dir+'/desktop.png'});
 await page.locator('#C04').scrollIntoViewIfNeeded();await page.screenshot({path:dir+'/card.png'});
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:dir+'/mobile.png'});
 await page.locator('#next').click();assert(page.url().endsWith('#C03'));checks.push('desktop/mobile layout and navigation');
 assert.deepEqual(errors,[]);checks.push('no page or console errors');
 const result={pass:true,url,browser:'Edge/Playwright; Browser plugin unavailable',checks,errors,untested:['native OS save picker','other browsers'],test_data:'isolated browser context; test exports are not user reviews'};
 fs.writeFileSync(dir+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});