const {chromium}=require('C:/Users/无语/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
const out='G:/youhegaojian/review-ui-qa/application001';
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text())});
 const checks=[];const check=(name,ok)=>{checks.push({name,pass:!!ok});if(!ok)throw Error(name)};
 const url='file:///G:/youhegaojian/macro-mind-engine/phase1/method_application/run_001/TRACE.html';
 await page.goto(url);
 check('identity',(await page.title())==='MacroMind｜冻结方法的首次应用');
 check('not_blank',(await page.locator('h1').innerText()).includes('可修正的判断'));
 check('no_error_overlay',await page.locator('vite-error-overlay,nextjs-portal').count()===0);
 check('five_methods',await page.locator('#application article').count()===5);
 check('two_judgments',await page.locator('#baseline article').count()===2);
 await page.screenshot({path:out+'/desktop.png'});
 await page.locator('#J01 a[href="#A22"]').click();
 check('reasoning_anchor',await page.evaluate(()=>location.hash==='#A22'));
 check('ancestor_details_auto_open',await page.locator('#A22').isVisible());
 await page.locator('#A22 a[href="#F2"]').click();
 check('news_evidence_visible',await page.locator('#F2').isVisible()&&await page.evaluate(()=>location.hash==='#F2'));
 await page.locator('nav a[href="#rules"]').click();
 const rule=page.locator('#rule-M02');await rule.locator('summary').nth(1).click();
 check('blogger_quotes_expand',await rule.locator('blockquote').first().isVisible());
 await page.screenshot({path:out+'/evidence.png'});
 check('all_internal_links_resolve',await page.locator('a[href^="#"]').evaluateAll(ns=>ns.every(n=>document.getElementById(n.getAttribute('href').slice(1)))));
 await page.goto(url+'#A41');check('direct_deep_link_opens',await page.locator('#A41').isVisible());
 await page.setViewportSize({width:390,height:844});await page.goto(url);
 check('mobile_no_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:out+'/mobile.png'});
 await page.locator('#J01 summary').click();check('mobile_update_conditions',await page.locator('#J01 details').getAttribute('open')!==null);
 check('mobile_expansion_no_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 check('console_health',errors.length===0);
 fs.writeFileSync(out+'/result.json',JSON.stringify({url,browser:'Edge / Playwright',browser_availability:'Browser plugin not available',flow:'baseline -> reasoning step -> news; fixed rule -> blogger quote; direct deep link; mobile update conditions',viewports:[[1440,1000],[390,844]],checks,errors},null,2));
 console.log(JSON.stringify({passed:checks.length,errors}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
