const {chromium}=require('C:/Users/无语/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert');
const dir='G:/youhegaojian/review-ui-qa/intake001';
(async()=>{
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage(),errors=[],checks=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const url='file:///G:/youhegaojian/macro-mind-engine/phase1/material_intake/conflict_001/INTAKE.html';
await page.goto(url);assert.equal(await page.title(),'MacroMind · 巴以冲突材料登记');assert.equal(page.url(),url);checks.push('identity');
assert.equal(await page.locator('article').count(),30);checks.push('30 records rendered, nonblank, no framework overlay');
await page.locator('#search').fill('454');assert.equal(await page.locator('article').count(),1);
await page.locator('summary').click();
await page.locator('[data-field=notes]').fill('测试备注，原字幕不修改');
await page.locator('[data-field=video_url]').fill('https://example.com/video');
await page.reload();await page.locator('#search').fill('454');await page.locator('summary').click();
assert.equal(await page.locator('[data-field=notes]').inputValue(),'测试备注，原字幕不修改');checks.push('edit and reload restores draft');
await page.locator('#bulkAcquisition').fill('测试批量来源');await page.locator('#apply').click();await page.locator('summary').click();
assert.equal(await page.locator('[data-field=acquisition]').inputValue(),'测试批量来源');
await page.locator('#search').fill('455');await page.locator('summary').click();
assert.notEqual(await page.locator('[data-field=acquisition]').inputValue(),'测试批量来源');checks.push('bulk edit scoped to filtered rows');
const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadPromise;await download.saveAs(dir+'/test-export.json');
const packet=JSON.parse(fs.readFileSync(dir+'/test-export.json','utf8'));assert.equal(packet.records.length,30);checks.push('JSON download contains all 30 records');
await page.locator('#search').fill('454');await page.locator('summary').click();await page.locator('[data-field=notes]').fill('changed');
page.on('dialog',d=>d.accept());
await page.locator('#file').setInputFiles(dir+'/test-export.json');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('已导入'));
await page.locator('summary').click();assert.equal(await page.locator('[data-field=notes]').inputValue(),'测试备注，原字幕不修改');checks.push('export import roundtrip');
const bad=structuredClone(packet);bad.records[0].id='wrong';fs.writeFileSync(dir+'/invalid.json',JSON.stringify(bad));
await page.locator('#file').setInputFiles(dir+'/invalid.json');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('导入失败'));
assert.equal(await page.locator('[data-field=notes]').inputValue(),'测试备注，原字幕不修改');checks.push('unknown record rejected without mutation');
const dup=structuredClone(packet);dup.records.push(dup.records[0]);fs.writeFileSync(dir+'/duplicate.json',JSON.stringify(dup));
await page.locator('#file').setInputFiles(dir+'/duplicate.json');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('重复'));checks.push('duplicate rejected');
await page.evaluate(()=>localStorage.clear());await page.reload();
await page.locator('#filter').selectOption('url');assert.equal(await page.locator('article').count(),30);
await page.locator('#filter').selectOption('notes');assert.equal(await page.locator('article').count(),0);checks.push('missing metadata and notes filters');
await page.locator('#filter').selectOption('all');
await page.screenshot({path:dir+'/desktop.png'});
await page.setViewportSize({width:390,height:844});await page.locator('summary').first().click();
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:dir+'/mobile.png'});checks.push('mobile no horizontal overflow');
assert.deepEqual(errors,[]);checks.push('no console or runtime errors');
const result={passed:true,browser:'Edge / Playwright; Browser plugin not available',url,viewports:['1440x1000','390x844'],checks,errors,untested:['native OS save picker; fallback download tested','other browsers']};
fs.writeFileSync(dir+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
